### ISSUE TITLE
Thumbnail not downloading causes ffmpeg error

### ISSUE THREAD

**Issue by commanderflatus** [jmbannon/ytdl-sub#307]
I'm getting an error trying to d/l hicock45's channel. Requested files attached. Appreciate any insight - I suspect it's my fault. Great app, btw. Thank you for the hard work.

[ytdl-sub.f_4f1jtv.txt](https://github.com/jmbannon/ytdl-sub/files/9896108/ytdl-sub.f_4f1jtv.txt)
[config.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/9896110/config.yaml.txt)
[ytdl-sub.f_4f1jtv.txt](https://github.com/jmbannon/ytdl-sub/files/9896111/ytdl-sub.f_4f1jtv.txt)

**Comment by commanderflatus** [comment]
[subscriptions.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/9896114/subscriptions.yaml.txt)

oops left this out

**Comment by commanderflatus** [comment]
Just to update. I used an online tool to get unique channel identifier and it still fails. Posted subscription.yaml had user-readable channel/user url. Thanks.

**Comment by jmbannon** [comment]
@commanderflatus did the issue ever resolve itself? Realized I already implemented retry on the thumbnail download - from the logs it looks like it downloaded

**Comment by commanderflatus** [comment]
I'm still getting the same error. Sorry for the delay in replying; having a busy weekend here.

**Comment by jmbannon** [comment]
No worries, same here. I will try to reproduce and see what's up

**Comment by commanderflatus** [comment]
deleting the tv_shows folder and re-downloading everything seems to be working now. looks like it was a permissions problem. feel free to close this ticket. I think some kind of advice re: permissions settings would be great because, like i said, docker permissions especially in unraid boggle my small brain. thanks again for the great project!

**Comment by jmbannon** [comment]
@commanderflatus See https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl_sub.config.config_validator.ConfigOptions.umask for apply permissions on output directory files

**Comment by commanderflatus** [comment]
Thank you. I fixed all the permission stuff, now it's happening again.

[config.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/9992601/config.yaml.txt)
[subscriptions.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/9992602/subscriptions.yaml.txt)
[ytdl-sub.sg8el8eu.txt](https://github.com/jmbannon/ytdl-sub/files/9992603/ytdl-sub.sg8el8eu.txt)
